# Generated by Django 2.1.11 on 2019-09-03 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20190828_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='post',
        ),
        migrations.AlterField(
            model_name='article',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='news.Tags'),
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
